qLDPCOrg/qLDPC

pyproject.toml

(for parity with https://github.com/Infleqtion/client-superstaq/pull/866)

always enforce modern annotation style

---

qldpc/codes.py

... rather than passing them to `np.array(field_array)`.  This is the preferred method:
```python
In [1]: import galois
In [2]: import numpy as np
In [3]: mat = galois.GF(2).Random((100, 100))
In [4]: %timeit np.array(mat)
488 ns ± 6.41 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [5]: %timeit mat.view(np.ndarray)
114 ns ± 1.12 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each
```

View galoir.FieldArray objects as numpy arrays

---

qldpc/codes.py
qldpc/codes_test.py
qldpc/decoder.py
qldpc/decoder_test.py

Also:
- fix some decoder bugs for nonbinary fields
- add stabilizer weight to list of code parameters
Codes extracted from PR #16, so credit also to @mittaltushant for their authorship.

Overhaul distance calculations and API

---

qldpc/abstract.py
qldpc/abstract_test.py
qldpc/named_codes.py
qldpc/named_groups.py
qldpc/named_groups_test.py

Identify number of `SmallGroup`s of a given order

---

qldpc/codes.py
qldpc/codes_test.py
qldpc/objects.py
qldpc/objects_test.py

Also test and ensure equivalency between chain-based, matrix-based, and graph-based `HGPCode` constructions.
Makes progress towards #33

Add `ChainComplex` object, and `ChainComplex.tensor_product`

---

qldpc/codes.py
qldpc/codes_test.py
qldpc/objects.py
qldpc/objects_test.py

I would like to check that this `GeneralizedSurfaceCode` has the correct number of qubits before merging though.
@oliverweissl: does this fix #33?

Add `GeneralizedSurfaceCode`

---

qldpc/codes.py
qldpc/codes_test.py
qldpc/objects.py
qldpc/objects_test.py

Also:
- allow passing a random number seed to `ClassicalCode.random`
- remove unreasonable defaults in a few quantum code constructors
Tagging @mittaltushant for visibility

Add random quantum Tanner codes

---

qldpc/codes.py
qldpc/codes_test.py

Also return `np.inf` for the distance of a trivial code.

Add five-qubit and steane codes

---

qldpc/codes.py
qldpc/codes_test.py

- Bug in `QCCode.get_check_shifts` with `open_boundaries=True`
- Bug in instantiating a `QCCode` with polynomials that contain only one symbol

Fix some `QCCode` bugs

---

qldpc/abstract.py

Further speeds up the construction of `QTCode`s

Faster `GroupMember` initialization

---

experiments/quasi_cyclic/make_summary_files.py
experiments/quasi_cyclic/run_search.py
qldpc/codes.py

and remove redundant codes from the quasi-cyclic code search

Add missing toric layouts to the `QCCode`s

---

checks/coverage_.py
pyproject.toml

... which has been [exported to](https://github.com/Infleqtion/client-superstaq/pull/966) (and subsequently [improved upon](https://github.com/Infleqtion/client-superstaq/pull/968)) in `client-superstaq`.

Improved modular coverage

---

checks/all_.py
checks/build_docs.py
pyproject.toml
qldpc/decoder.py

Addresses #133 by pinning prior version.

Pin working `ldpc` dependency

---

qldpc/circuits.py
qldpc/circuits_test.py

... with a brute-force search.  So horrible runtime, but useful at small-to-moderate scale.

Find a physical transversal circuit for a logical Clifford, if possible

---

qldpc/external/__init__.py

add gap to external/__init__.py

---

qldpc/codes/classical.py
qldpc/codes/common.py
qldpc/codes/common_test.py
qldpc/codes/quantum.py
qldpc/codes/quantum_test.py

Also clean up and standardize code and docstrings for distance calculations in `ClassicalCode`s and `CSSCode`s

Add (brute force) calculation of code distance for QuditCodes

---

qldpc/codes/common.py
qldpc/codes/common_test.py
qldpc/codes/quantum.py
qldpc/codes/quantum_test.py

Also standardize some ClassicalCode/QuditCode/CSSCode methods.

Add code cannonicalization and validation

---

qldpc/circuits.py
qldpc/circuits_test.py
qldpc/codes/common.py
qldpc/codes/common_test.py
qldpc/codes/quantum_test.py
qldpc/objects.py
qldpc/objects_test.py

Also (this is bad practice but) clean up some test files/functions

Add capability to deform a code by physical Clifford operations

---

qldpc/circuits.py

Make `circuits.get_encoding_circuit` encode arbitrary states of a code

---

qldpc/circuits_test.py
qldpc/codes/common.py
qldpc/codes/common_test.py
qldpc/codes/quantum.py
qldpc/codes/quantum_test.py

Also other test+coverage fixes, for example when setting `DEFAULT_FIELD_ORDER=3`

Fix qudit surface/toric codes

---

examples/find_bbcode_layouts.py

@jmlarson1 I still have a TODO at the bottom that I'll add to this PR, but you can work on this branch for a much nicer interface for getting qubit locations:
```python
layout_params = find_layout_params(code, folded_layout)
max_distance = get_max_comm_distance(code, layout_params)
print("max_distance:", max_distance)
get_qubit_pos = get_qubit_pos_func(code, layout_params, max_distance)
for node in code.graph.nodes:
print(node, get_qubit_pos(node))
```
UPDATE: I finished the TODO.  Check out `get_completed_qubit_pos_func`.

More speedups and a nicer a nicer user interface in `find_bbcode_layouts.py`

---

examples/find_bbcode_layouts.py

Fix missing part of `BBCode` layout search space

---

examples/basics.ipynb
examples/bivariate_bicycle_codes.ipynb
examples/logical_errors.ipynb
examples/transversal_gates.ipynb

pip install to jupyter environment inside notebooks

---

.github/workflows/ci.yml
pyproject.toml

version bump to deploy the bugfix in #217
and since this PR changes `pyproject.toml`, it's a good place to test (and fix) #213

fix workflow caching and version bump

---

qldpc/codes/common.py
qldpc/decoders.py
qldpc/decoders_test.py

...and use `DirectDecoder`s for computing logical error rates

rename MeasurementDecoder to DirectDecoder

---

qldpc/decoders.py
qldpc/decoders_test.py

Largely as described in https://arxiv.org/pdf/2103.08049, and generalized to nonbinary fields.

Add generalized Union-Find decoder

---

qldpc/decoders.py
qldpc/decoders_test.py
qldpc/objects.py

And add a warning when initialized without a `max_weight`

Extend `LookupDecoder` to `QuditCode`

---

pyproject.toml

- add `cython` to the `[dev]` extra of `qldpc`
- make a `[gurobi]` extra of `qldpc`

Rearrange optional dependencies

---

build-cython.py

And change default arguments for the `msvc` compiler.

Add option to override C compiler arguments

---

qldpc/codes/_distance.pyx
qldpc/codes/classical.py
qldpc/codes/common.py
qldpc/decoders.py

should fix everything broken by numpy 2.0.0. also fixes an [overflow error](https://github.com/Infleqtion/qLDPC/actions/runs/14965409700/job/42034414464) in `_distance.pyx`

numpy 2.0 support + bugfix

---

qldpc/abstract.py
qldpc/abstract_test.py
qldpc/codes/common.py
qldpc/codes/quantum.py
qldpc/codes/quantum_test.py
qldpc/objects_test.py

abstract.Groups no longer have fields attached to them.  That is taken care of by the GroupRing.

Add `abstract.GroupRing`

---

pyproject.toml

This is largely to fix #335 on the PyPI version of `qldpc`

version bump to v0.2.1

---

qldpc/circuits/__init__.py
qldpc/circuits/common.py
qldpc/circuits/common_test.py
qldpc/circuits/memory.py
qldpc/circuits/memory_test.py
qldpc/circuits/syndrome_measurement.py
qldpc/circuits/syndrome_measurement_test.py

Essentially merge the changes in #346 that are more about refactoring and rearranging code, rather than fixing #319

Clean up memory experiments and related code

---

qldpc/circuits/__init__.py
qldpc/circuits/bookkeeping.py
qldpc/circuits/bookkeeping_test.py
qldpc/circuits/common.py
qldpc/circuits/memory.py
qldpc/circuits/syndrome_measurement.py

to keep track of QubitIDs, MeasurementRecord, and DetectorRecord

add circuits/bookkeeping.py

---

qldpc/decoders/__init__.py
qldpc/decoders/custom.py
qldpc/decoders/custom_test.py
qldpc/decoders/decoders.py
qldpc/decoders/decoders_test.py

Also require passing a max_weight

Merge LookupDecoder and WeightedLookupDecoder
