- qldpc/codes.py
- qldpc/codes_test.py
This calculation is brute-force:
- generate all words in the code
- return the minimum weight (number of nonzero entries) of all nontrivial words
> Add distance calculation for classical codes with non-binary fields

- qldpc/codes.py
- qldpc/codes_test.py
- qldpc/decoder.py
More or less the same algorithm as before works, but now rather than looking for anti-commutation between X-type and Z-type logical operators, we look for the condition that `X(1)*Z(1) = w*Z(1)*X(1)`, where `w = exp(2 pi i / q)` for a `q`-dimensional qudit.
If we consider the generalized `n`-qudit Pauli strings `X(a)` and `Z(b)`, where now `a` and `b` are vectors in `F_q^n` and (say) `X(a) = \bigotimes_j X^{a_j}`, then the requirement `X(a)*Z(b) = w*Z(b)*X(a)` implies `a @ b = 1`.
Once we can construct logical operators, we can also compute exact code distance with an integer linear program (in the case of prime number fields).
> Generalize calculation of logical qubit operators to the qudit case

- qldpc/codes.py
- qldpc/codes_test.py
Based on the construction in Section 4.1 of [Gottesman's thesis](https://arxiv.org/abs/quant-ph/9705052).
Some benchmarking (with memoization turned off):
```python
In [237]: code = codes.HGPCode(codes.ClassicalCode.random(30, 25))
In [238]: %timeit code.old_get_logical_ops()
4.11 s ± 353 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [239]: %timeit code.new_get_logical_ops()
258 ms ± 39.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
> Faster logical operator construction

- checks/coverage_.py
This makes coverage more modular.
This requirement may be relaxed in the future, if it becomes a significant obstacle to development.  But I may as well enforce modular coverage while I can.
> Require that each file is covered by its own test file

- qldpc/abstract.py
- qldpc/abstract_test.py
- qldpc/codes.py
Ported from @mittaltushant's `experiment_cyclic_hamming` branch, with a bit of cleanup
> Add DicyclicGroup, GAP16, GAP18, and GAP20

- qldpc/codes.py
Also allow specifying an operator type in `CSSCode.get_logical_ops()`.  For example, `code.get_logical_ops(Pauli.X)` will now just return the X-type operators.
> Fix bug in random nontrivial logical operator construction

- qldpc/codes.py
- qldpc/codes_test.py
- qldpc/objects.py
Tagging @mittaltushant for visibility, since this is something you have asked about before :slightly_smiling_face:
I'm still defining `CayleyComplex`es with directed graphs though, just because I think these are more "natural" objects to consider :shrug:
> Add construction of Tanner codes with undirected subgraphs

- qldpc/codes.py
- qldpc/codes_test.py
Also change GBCode conventions (for consistency with [arXiv:2012.04068](https://arxiv.org/abs/2012.04068), [arXiv:2308.07915](https://arxiv.org/abs/2308.07915), and [arXiv:2311.16980](https://arxiv.org/abs/2311.16980)) and change some sign conventions in qudit `HGP/LPCode`s to make them consistent with `GBCode`.
> Fix bug in GBCode with qudits

- qldpc/codes.py
- qldpc/codes_test.py
These methods will be used in code-search experiments.
Also: added equality testing between `ClassicalCode`s, and added the `ClassicalCode.from_generator` constructor.
@mittaltushant no rush, but if you get the chance can you please take a quick look to make sure this looks correct?
> Puncture and shorten `ClassicalCode`s

- qldpc/codes.py
- qldpc/codes_test.py
Per [this comment](https://github.com/Infleqtion/qLDPC/pull/41#issuecomment-2020470622), `ClassicalCodes.__eq__` now checks exact equality between code **_instances_**, while `ClassicalCode.equiv` checks whether they are "equivalent", meaning that the two codes contain each other (or: have the same set of code words).
> Change equality check between ClassicalCode instances

- qldpc/codes.py
- qldpc/codes_test.py
- qldpc/objects.py
Methods taken from [arXiv:2308.07915](https://arxiv.org/abs/2308.07915) (page 12)
> Identify "toric" layouts of quasi-cyclic codes (`QCCode`s)

- qldpc/abstract.py
- qldpc/abstract_test.py
... which now builds a protograph from a matrix with entries that are
(a) elements of the group algebra,
(b) group members, or
(c) integers.
> More permissive `Protograph.build`

- qldpc/abstract.py
Random subset generation should be deterministic when passed a random number seed.  This method previously used `set.pop`, which is not deterministic.
> Fix random symmetric subset generation

- qldpc/abstract.py
- qldpc/abstract_test.py
- qldpc/external/codes.py
- qldpc/external/groups.py
- qldpc/external/groups_test.py
For example, `qldpc.abstract.SmallGroup(12, 1).structure == "C3 : C4"`
> Retrieve `SmallGroup` structure descriptions

- qldpc/codes/common.py
- qldpc/codes/common_test.py
This also speeds up the calculation of dimension for codes with a base field > 2, because it now uses Gaussian elimination rather than an SVD decomposition.
> Identify the dimension of qudit codes

- qldpc/codes/quantum.py
The previous construction was rather confusing, leading to errors in the explanations (in comments/docstrings) of what was going on.
> Clean up graph construction of HGP product

- qldpc/abstract.py
- qldpc/abstract_test.py
The `ProjectiveSpecialLinearGroup` class works in any dimension `2, 3, 4, ...`:
- If `linear_rep == True `, the constructor uses a permutation representation acting on cosets of the standard representation of the `SpecialLinearGroup`.
- If `linear_rep == False`, the constructor uses the adjoint representation.
> Additions to the group PSL.

- README.md
- qldpc/codes/__init__.py
- qldpc/codes/quantum.py
- qldpc/codes/quantum_test.py
`GBCode`s are a special case of `TBCode`s.  The construction implemented in this library was in fact that of a `TBCode`.
> Rename generalized bicycle code (GBCode) to two-block code (TBCode)

- qldpc/codes/common.py
- qldpc/codes/common_test.py
- qldpc/codes/quantum.py
- qldpc/codes/quantum_test.py
(... yet again)
The motivation here is be consistent in having `n`-qubit operators represented by `2n`-bit strings in which the first (last) `n` bits indicate the support of X-type (Z-type) operators.  In order to extract, say, `syndrome = parity_check_matrix @ error` for a `n`-qubit error operator, we therefore need the rows of the parity check matrix to look like `[z_support|x_support]`.
> Change conventions for `CSSCode.matrix`

- pyproject.toml
- qldpc/codes/common.py
- qldpc/codes/common_test.py
Logical operators, even for `CSSCode`s, are now always organized into `[x_support | z_support]`.
> Change logical operator format

- qldpc/abstract.py
- qldpc/abstract_test.py
Override `Protograph.__matmul__` to keep track of the base group of protographs.
> Protograph bugfixes

- qldpc/codes/common.py
- qldpc/codes/common_test.py
- qldpc/codes/quantum.py
- qldpc/codes/quantum_test.py
These arguments were adding clutter that wasn't justified by the (in)significance of qudit conjugation.  This PR `QuditCode.conjugated` methods to support local qudit conjugation.
> Remove conjugated argument from `QuditCode.__init__` methods

- qldpc/abstract.py
- qldpc/cache.py
- qldpc/cache_test.py
- qldpc/codes/common.py
- qldpc/codes/common_test.py
- qldpc/external/codes_test.py
- qldpc/external/groups.py
- qldpc/external/groups_test.py
I previously stripped functions of their cache wrapper in `*_test.py` files.  This PR instead makes the `qldpc.cache.use_disk_cache` decorator recognize whether it's being run with pytest and behave accordingly.
> Clean up interactions between cache and pytest

- qldpc/codes/common.py
- qldpc/codes/common_test.py
The distance bounding methods will stop trying to find a tighter bound on code distance if it finds a distance <= a provided cutoff.
> Add early stopping to `*Code.get_distance_bound` methods

- examples/find_optimal_communication_distance.py
If this graph is always bipartite (which I think is the case) then this matching algorithm should be faster. 
Timing for me on the following case: 
```
(n, k): (288, 12)
orders: {x: 12, y: 12}
poly_a: x**2/y**3 + x + 1
poly_b: x**3*y**2 + y + 1
```
was about 15% faster... so if such a change isn't significant enough, then feel free to close this PR.
> Using a bipartite matching algorithm

- qldpc/circuits.py
I wonder why the type checker doesn't catch this. :thinking:
> Fix return type of `get_encoding_tableau`

- .github/workflows/ci.yml
- qldpc/codes/common.py
The format and lint was spending < 1 second on the check, and pretty much all of its time on package installation.  This PR just merges it with the type checker.  The corresponding workflow runs all three checks unconditionally, and reports which of them failed (if any).
> combine linting and type checking workflows

- qldpc/circuits.py
- qldpc/circuits_test.py
- qldpc/codes/common.py
- qldpc/codes/common_test.py
The full [X|Z] support is returned by, for example, `code.get_logical_ops(Pauli.X, symplectic=True)`
> Return only X/Z support of `code.get_logical_ops(Pauli.[X/Z])` for `CSSCode`s

- qldpc/codes/common.py
- qldpc/codes/common_test.py
`QuditCode.get_distance_exact` previously only computed the minimum weight of **_pure_** logicals.  Oops.  They should instead compute the minimum weight of [logicals] mod [stabilizers and gauge ops].
This PR also fixes a minor bug in the construction of logical operators for non-CSS subsystem codes; namely that [this line](https://github.com/Infleqtion/qLDPC/blob/c88cc575707291a676b6ef94d42ebe6c1846c3c7/qldpc/codes/common.py#L1113) could cause `matrix_x` to have Z-type gauge ops (because the operators in `checks_x` may contain factors of Z-type gauge ops).  Those gauge ops can just be [removed](https://github.com/Infleqtion/qLDPC/blob/1bdde8a8965ac68c9891eadb24a854f0ebfea74a/qldpc/codes/common.py#L1113).
> fix bug in subsystem code distance calculation

- qldpc/circuits.py
- qldpc/circuits_test.py
- qldpc/codes/common.py
- qldpc/math.py
- qldpc/math_test.py
- qldpc/objects.py
- qldpc/objects_test.py
There is now a cleaner separation: `qldpc.objects` includes custom classes, while `qldpc.math` has various utility functions.
> move `op_to_string` to `qldpc.math`

- qldpc/codes/_distance.pyx
Caught by @richrines1 [here](https://github.com/Infleqtion/qLDPC/issues/248#issuecomment-2802903244).  It would be nice to think of a simple test that catches this bug...
> Fix bug in calculation of code distance for non-CSS codes

- qldpc/codes/common_test.py
- qldpc/codes/quantum.py
- qldpc/codes/quantum_test.py
All Toric codes have redundant checks, but the case of the rotated 2x2 Toric code is particularly egregious -- some checks are *equal* to others -- so remove the redundant checks in this case.
> Simplify rotated 2x2 Toric code

- qldpc/abstract.py
- qldpc/abstract_test.py
New strategy: intercept numpy methods `__array_finalize__` and `__array_ufunc__` to set `_group` as appropriate
> Add missing arithmetic for protographs

- qldpc/abstract.py
- qldpc/abstract_test.py
- qldpc/codes/quantum.py
This attribute was previously unset when using operations like `np.block` and `np.kron`.  That is fixed by adding a `Protograph.__array_function__` method.
> Propagate Protograph _group attribute

- qldpc/abstract.py
- qldpc/abstract_test.py
- qldpc/codes/quantum.py
- qldpc/codes/quantum_test.py
- qldpc/objects.py
- qldpc/objects_test.py
Make `abstract.Element` and `abstract.Protograph` subclass accordingly and raise deprecation warnings.
> Rename `Element -> RingMember` and `Protograph -> RingArray`

- checks/all_.py
- checks/format_.py
- checks/lint_.py
- pyproject.toml
With the resolution of https://github.com/Infleqtion/client-superstaq/issues/1195, `checks-superstaq==0.5.45` contains some changes to make `ruff` the default formatter and linter for `checks-superstaq`. In doing so, `ruff_format_.py` is now `format_.py` and `ruff_lint_.py` -> `lint_.py`. 
This PR makes the corresponding changes for `qLDPC`.
> Update `checks/` to support `checks-superstaq>=0.5.45`

- qldpc/codes/common.py
- qldpc/codes/common_test.py
... to make the naming consistent with https://errorcorrectionzoo.org/c/quantum_concatenated and https://errorcorrectionzoo.org/list/quantum_concatenated.
After this PR, the "outer" code is the one that acts on physical qudits, and the logical qudits of the "outer" code are used as the physical qudits of the "inner" code.
> Swap "inner" and "outer" naming conventions for concatenated codes

- qldpc/codes/distance_test.py
When using python 3.10.12 in fresh environment on wsl ubuntu 22.04, tests will fail with this error:
File "/mnt/c/Users/Ryan/Desktop/qLPDC_PR/qLDPC/qldpc/codes/distance_test.py", line 219
packed_bits = bits[*indices[:-1]][i : i + nbits]
^
SyntaxError: invalid syntax
It seems being able to unpack a tuple in an index operator was established in[ this PEP](https://peps.python.org/pep-0646/
), but is only valid for python3.11 onwards. 
This commit fixes this issue by removing unpacking operator- numpy [recognizes](https://numpy.org/devdocs/user/basics.indexing.html) and unpacks tuples when indexing
> Fix unpacking issue for python3.10

- pyproject.toml
Some parts of `qldpc==0.2.0` depend on `stim>=1.15.0`.  See [comment](https://github.com/qLDPCOrg/qLDPC/issues/335#issuecomment-3203151644).
Fixes #335 (I think)
> Update stim dependency

- qldpc/codes/common.py
- qldpc/codes/common_test.py
Inspired by [this answer](https://www.linkedin.com/feed/update/urn:li:activity:7372388858019340288?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7372388858019340288%2C7372410478708445184%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7372388858019340288%2C7372417375561973760%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287372410478708445184%2Curn%3Ali%3Aactivity%3A7372388858019340288%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287372417375561973760%2Curn%3Ali%3Aactivity%3A7372388858019340288%29) to [this question](https://www.linkedin.com/posts/dillonmontero_been-trying-to-do-a-literature-search-and-activity-7372388858019340288-FW0x?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAsz0DEBkzdCiKElJIsP-E9nqs2eIWVrQC4).
> Rename `QuditCode.get_dual_subsystem_code` to `QuditCode.dual`

- qldpc/codes/common.py
- qldpc/codes/common_test.py
We previously had `CSSCode.set_logical_ops_xz`.  This method was redundant in that once X-type logicals are defined, there is no choice of Z-type logicals, and vice versa.
This PR adds `CSSCode.set_logical_ops_x` and `CSSCode.set_logical_ops_z`, which automate the construction of logicals in one sector once the logicals in the other sector are defined.
Still a TODO (in a future PR) is to fill in `QuditCode.set_logical_ops_[x|z]`, which currently raise a `NotImplementedError`.  These methods are somewhat more mathematically involved, but look like a fun linear algebra problem to solve sometime.
> Allow setting X-type logicals of a CSS code, determining the Z-type logicals automatically

- qldpc/codes/common.py
- qldpc/codes/common_test.py
The exact distance calculation will stop and return early if an upper bound on distance drops to or below this cutoff.  In this case, the returned value is the upper bound.
> Allow passing a cutoff to `QuditCode.get_distance_exact`

- qldpc/decoders/custom.py
- qldpc/decoders/custom_test.py
- qldpc/decoders/sinter.py
The LookupDecoder will automatically build a maximum-likelihood penalty function
> Allow passing an error_channel to a LookupDecoder
